const resList = [
  {
    URL: "http://www.just-eat.co.uk/restaurants-cn-chinese-cardiff/menu",
    _id: { $oid: "55f14312c7447c3da7051b26" },
    address: "228 City Road",
    addressLine2: "Cardiff",
    name: ".CN Chinese",
    outcode: "CF24",
    postcode: "3JH",
    rating: 5,
    typeOfFood: "Chinese",
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-atthai-ss9/menu",
    _id: { $oid: "55f143s12c7447c3da7051b27" },
    address: "376 Rayleigh Road",
    addressLine2: "Essex",
    name: "@ Thai",
    outcode: "SS9",
    postcode: "5PT",
    rating: 5.5,
    typeOfFood: "Thai",
    id: 1,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-atthairestaurant/menu",
    _id: { $oid: "55f1431d2c7447c3da7051b28" },
    address: "30 Greyhound Road Hammersmith",
    addressLine2: "London",
    name: "@ Thai Restaurant",
    outcode: "W6",
    postcode: "8NX",
    rating: 4.5,
    typeOfFood: "Thai",
    id: 2,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-indiancom-ch4/menu",
    _id: { $oid: "55f1431s2c7447c3da7051b2a" },
    address: "9 Broughton Hall Road",
    addressLine2: "Broughton",
    name: "@Indian.com",
    outcode: "CH4",
    postcode: "0QR",
    rating: 6,
    typeOfFood: "Curry",
    id: 3,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-007takeaway-s65/menu",
    _id: { $oid: "55f14312c7447c3daf7051b2b" },
    address: "6 Drummond Street",
    addressLine2: "Rotherham",
    name: "007 Takeaway",
    outcode: "S65",
    postcode: "1HY",
    rating: 6,
    typeOfFood: "Pizza",
    id: 4,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-042-restaurant-e11/menu",
    _id: { $oid: "55f143a12c7447c3da7051b2c" },
    address: "885 High Road Leytonstone",
    addressLine2: "London",
    name: "042 Restaurant & Bar",
    outcode: "E11",
    postcode: "1HR",
    rating: 3,
    typeOfFood: "African",
    id: 5,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-1-2-3-chinese-rowlands-gill/menu",
    _id: { $oid: "55f14312c7447c3dada7051b2f" },
    address: "Unit 4 Spencer House",
    addressLine2: "Swalwell",
    name: "1 2 3 Chinese",
    outcode: "NE16",
    postcode: "3DS",
    rating: 4.5,
    typeOfFood: "Chinese",
    id: 6,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-100-degrees-chinese-restaurant-pontypridd/menu",
    _id: { $oid: "55f143a12c7447c3da7051b31" },
    address: "67 Park Street",
    addressLine2: "Treforest",
    name: "100 Degrees Chinese Restaurant",
    outcode: "CF37",
    postcode: "1SN",
    rating: 5,
    typeOfFood: "Chinese",
    id: 7,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-104-turkish-BBQ/menu",
    _id: { $oid: "55af14312c7447c3da7051b33" },
    address: "104 Tanners Lane",
    addressLine2: "Essex",
    name: "104 Turkish BBQ",
    outcode: "IG6",
    postcode: "1QE",
    rating: 5,
    typeOfFood: "Turkish",
    id: 8,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-109restaurant-w2/menu",
    _id: { $oid: "55f14312c7447c3dad7051b34" },
    address: "109 Westbourne Park Road",
    addressLine2: "London",
    name: "109 Ristorante",
    outcode: "W2",
    postcode: "5QL",
    rating: 5,
    typeOfFood: "Pizza",
    id: 9,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-113-fish-bar-wallasey/menu",
    _id: { $oid: "55f14312ac7447c3da7051b35" },
    address: "113 Poulton Road",
    addressLine2: "Merseyside",
    name: "113 Fish Bar",
    outcode: "CH44",
    postcode: "9DE",
    rating: 5.5,
    typeOfFood: "Chinese",
    id: 10,
  },
  {
    URL: "http://www.just-eat.co.uk/restaurants-133-takeaway-irvine/menu",
    _id: { $oid: "55f14312c7447dc3da7051b36" },
    address: "133 Fullarton Street",
    addressLine2: "Irvine",
    name: "133 Takeaway",
    outcode: "KA12",
    postcode: "8DG",
    rating: "Not yet rated",
    typeOfFood: "Breakfast",
    id: 11,
  },
];

export default resList;
